### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Flurrywinde** [ChoicescriptIDE/main#10]
Now that I can get cside to compile, I'd like to help fix bugs and/or add features. I am, however, not yet familiar with node or NW.js, so I'll have to learn about these things along the way. Can you tell me the basic structure of the code? Is `/index.html` the main interface with all the code for what it does in `source/mods/`? Or how does it work? What's `source/js/`?

If I wanted to implement on of the feature requests (https://choicescriptide.github.io/discuss/request-feature/), would you be willing to point me in the right direction? For example, this: [http://disq.us/p/1k8dtmt](http://disq.us/p/1k8dtmt), which is me wanting to add a variable that equates line of code with line of game output to quickly jump to where typos are.

**Comment by CareyJWilliams** [comment]
I'd love to see other people contributing, but I have to admit that the CSIDE codebase is far from stellar. It's getting old and pretty monolithic in nature. I'm a better programmer now than I was when I started, but technical debt has a nasty way of catching up with you. Honestly, if I had unlimited time, I would once again rewrite the whole thing (probably in reactJS), but that's not on the cards at the moment.

Anyway, yes, I'm more than happy to point you at certain things, in fact I'd _rather_ you talk to me first - just so you don't waste time doing something I can't/won't include (for good reason, of course). For example, I really don't think that particular feature can be done in a _clean_ way (though I'd be happy to be proven wrong).

Anyway, to start, read up on NodeJS, CodeMirror (JS editor library) and KnockoutJS (MVC library). The two most important files are index.html, which contains the interface markup and their associated bindings. The model/controller (logic) code is mostly in js/knockoutCSIDE.js.

ChoiceScript wasn't designed to be modular, so we have a modified version of that (and CodeMirror, though for different reasons) under the CSIDE Github organisation. There are also a number of overrides in some /mod/ files and js/cs_override.js - but I really want to get away from overriding, as it's causing a lot of hidden bugs whenever those original functions are updated in the original CS.

**Comment by Flurrywinde** [comment]
Awesome. I'll get studying. As for the feature I especially want, yeah, I probably should start with something simpler.

**Comment by CareyJWilliams** [comment]
I've added you to a team under the organisation; if you get any ideas (features, bug fixes or anything else), create an issue for discussion, fork to implement, and we can pull request to include it once it's been reviewed :)

**Comment by Flurrywinde** [comment]
Great! Will do.
