### ISSUE TITLE
After fresh install and updating, at startup, instead of loading the app I get nw.js window

### ISSUE THREAD

**Issue by max-torch** [ChoicescriptIDE/main#105]
I downloaded and installed cside_setup_x64_v101.exe
After installation I ran ChoiceScript IDE
The app loads with the UI window and everything.
At bottom right of the app it tells me to click to update to latest version. After updating it tells me to restart the app.
Now whenever I run ChoiceScript IDE I am presented with a Chromium window which says nw.js in the middle:
![image](https://user-images.githubusercontent.com/41433185/96338893-920e2600-10c3-11eb-81c9-082a275f105e.png)
Please help me fix this so that I can experience CSIDE.

My system details are:
![image](https://user-images.githubusercontent.com/41433185/96338956-05179c80-10c4-11eb-966f-2f755fade9a9.png)
I am logged in using an Administrator account

**Comment by CareyJWilliams** [comment]
Navigate to your install folder and look for:
- A file called package.nw
- A file called prev-package.nw

Rename prev-package.nw to package.nw. This will 'rollback' the update. If the issue persists every time you update, please come back to me.

**Comment by max-torch** [comment]
> Navigate to your install folder and look for:
> 
> * A file called package.nw (let me know if this exists)
> * A file called prev-package.nw
> 
> Rename prev-package.nw to package.nw. This will 'rollback' the update. If the issue persists every time you update, please come back to me.

This solved the problem. I am now at CSIDE v1.3.1
I wouldn't at all have known to do this if you had not advised me to.

**Comment by CareyJWilliams** [comment]
Glad to hear it. It's very rare that someone would need to do this, so it's not documented anywhere. Most likely your first attempt to update was interrupted/corrupted somehow.

Thanks for raising the issue. I hope you enjoy CSIDE!
