### ISSUE TITLE
Building on Mac, get unusable UI

### ISSUE THREAD

**Issue by KLNeidecker** [ChoicescriptIDE/main#11]
When building on Mac, OS X (MacOS Sierra) the UI is broken.

Steps:
- clone repo
- npm install
- get a few warnings:
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN grunt-execute@0.2.2 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN CSIDE@1.0.1 No repository field.
npm WARN CSIDE@1.0.1 No license field.
```
- grunt build-with-mac
- (get an error about not finding the CS files Error: ENOENT: no such file or directory, open 'build/node_modules/cside-choicescript/web/mygame/index.html')
- Copied CS files to said location (newest CS files, copy directory in full, rename to cside-choicescript)
- grunt build-with-mac again, works this time

But when run, the UI is completely messed up. [https://www.evernote.com/l/ABP7JMzEC81CA5cFFB0gJhvcR77phsuEGCQB/image.png](url)

A bunch of commits ago, I managed to build it with correct UI, but never before that or after.

**Comment by CareyJWilliams** [comment]
Thanks for reporting this. The CS issue sounds similar to what @flurrywinde encountered in #10. I think that warrants another close look.

The UI tends to end up like that when some other JS error prevents the app from fully loading. I didn't think the current build was broken. I'll take a look myself, but if you're building for Dev (should be the default I think), you should be able to right-click and inspect element to access a JS console just like you would in Chrome. The error in question is likely hiding there.

**Comment by CareyJWilliams** [comment]
@KLNeidecker A fresh clone built fine for me on Mac OS X El Capitan.

**Comment by CareyJWilliams** [comment]
@Flurrywinde @KLNeidecker 
Please accept my apologies, on deeper digging I've discovered there was indeed something wrong with the build process. I didn't realise as the process didn't always start from a clean build directory (so failed to pick up the missing files!). I'll be committing a fix for this shortly, again, I'm awfully sorry about that. Thanks for bringing it to attention!

**Comment by CareyJWilliams** [comment]
Closed by https://github.com/ChoicescriptIDE/main/commit/8d84673f44d19a6540d3fbdd371c52af3ca3f6c8
