### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by jeremydouglass** [ChoicescriptIDE/main#110]
Could this repo host the latest (1.4.0) release?

Currently the commit history references v1.4.0 +, but the latest release on this repo releases is v1.0.1 (2017). When I downloaded 1.0.1, it prompted to download an update to v1.3.1 and restart. When I did, Settings > App Settings > Version lists 1.3.1 -- although the About > ChoiceScriptIDE lists 1.0.0. However, it looks like 1.3.1 is June 2019.

**Comment by CareyJWilliams** [comment]
Hi Jeremy, this is because v.1.4.0 is still in active development. Development is transparent, so you're free to download the source code and build the latest changes yourself. However, it will be some time before a new version is officially declared.

Thank you for interest!

CJW

**Comment by jeremydouglass** [comment]
Thanks so much, @CareyJWilliams -- sorry for the delayed reply. I greatly appreciate you making ChoiceScript IDE available and all your work on it.

Is 1.0.1 the latest stable release, then, or is that 1.3.1? -- and if I was going to build 1.3.1, which commit should I build from? (it is not tagged)

I'm trying to think through a class workshop in which a large group of students each download and install ChoiceScript IDE, and I'd rather not have them go through an install-then-upgrade if upgrading is avoidable -- one less thing to break.

**Comment by CareyJWilliams** [comment]
v1.3.1 should be in widespread use, yes.
I'd build from:
e9e746c613490b448fa82fa88ea9cf45c841c966

But I'd also hope that the updating isn't *that* unreliable!

**Comment by jeremydouglass** [comment]
Thanks!

Re updating: I'm sure your update mechanism is fine, it worked perfectly for me -- it is just that multiple extra steps in setup instruction especially in a large group tends to create PEBCAK problems.
