### ISSUE TITLE
Opening file in CSIDE from right-click menu in Finder does not work properly

### ISSUE THREAD

**Issue by CareyJWilliams** [ChoicescriptIDE/main#15]
Submitter: Fiogan
When using 'open file in CSIDE' from right-click menu, the scene file appears in the Scenes and Projects Tab with '%20' instead of spaces in the enclosing folder names. The scene won't open properly in the Editor Window, or Run in the usual manner.

**Comment by CareyJWilliams** [comment]
@Fiogan should be fixed by: https://github.com/ChoicescriptIDE/main/commit/ce6cea5045cf493fd727b75f4dd53e7c34ca3598 - thanks for reporting!

**Comment by Fiogan** [comment]
I tried to open a .txt file in CSIDE via right-click (development version of CSIDE, Mac with current OS) and the menu options no longer permit me to open .txt files with CSIDE, even when I try to select the application manually.

<img width="933" alt="screen shot 2017-10-18 at 09 57 37" src="https://user-images.githubusercontent.com/27186623/31725829-ebcc4462-b3ea-11e7-86b4-fc7e4b6a0cca.png">
