### ISSUE TITLE
Fixing mixed tabs and spaces / indentation buggy

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#18]
Reported by GoldenSilver of the CoG forums [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/299?u=fiogan):

Imported text files into CSIDE; the files had previously been edited in Notepad++.

CSIDE identified both spaces and tabs. Ran auto-fix, and the text bodies beneath choices were no longer indented, like so:

```

*choice
  #Option one.
  Text body.
  *goto end
  #Option two.
  Text body.
  *goto end
*label end

```

Tried switching from spaces to tabs but it didn't fix the problem.

**Comment by CareyJWilliams** [comment]
Closing as this functionality was disabled by: https://github.com/ChoicescriptIDE/main/commit/31af16ee81438838c9afa07edf2d9672d44b0030

No plans to re-enable it (or an equivalent) anytime soon.
