### ISSUE TITLE
Request for additional hotkeys: comment, duplicate, erase

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#19]
Request from GoldenSilver at CoG forums [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/299?u=fiogan):

Hotkey to comment line.
Hotkey to duplicate line.
Hotkey to erase line.

**Comment by CareyJWilliams** [comment]
Implemented with: https://github.com/ChoicescriptIDE/main/commit/7f272d7f5eaa7f0b4061cdc4e5999aaa5aef6c42
