### ISSUE TITLE
Spell check adjustment?

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#20]
Request from GoldenSilver of the CoG forums [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/299?u=fiogan):

Make the spell check disable for things like variables after *create, *set, *label, *goto and such.

**Comment by Fiogan** [comment]
I also noticed that spell check actually says it excludes option and command lines, but currently, it doesn't. Per here:

<img width="965" alt="screen shot 2017-11-04 at 14 42 55" src="https://user-images.githubusercontent.com/27186623/32408924-32ffc872-c16f-11e7-9061-5ed2942e304a.png">

(As you know, I quite like the fact that spellcheck does check my option and command lines; I would be in a desperate muddle if CSIDE didn't…so if that changes, I would love for it to be an optional change adjustable via the ever-growing Settings. I really need spellcheck in my command and option lines, personally.)

**Comment by CareyJWilliams** [comment]
I've made spellcheck a three way variable setting, in a very similar manner to word count: https://github.com/ChoicescriptIDE/main/commit/359c6ee7d669d2542137585c94e03602a64bcffd
