### ISSUE TITLE
'Insert double line break' indentation bug

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#22]
Reported by GoldenSilver of the CoG forums [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/299?u=fiogan)

> The “insert double line break” function does not insert into indentation correctly. Making you have to fix the indentation of the line breaks if you are inside a *choice or *if.

**Comment by CareyJWilliams** [comment]
Fixed by: https://github.com/ChoicescriptIDE/main/commit/4f7cc463f379ba980beee675cfcc3e9b274f634c
