### ISSUE TITLE
Request for change to search function: CTRL/CMD+G vs. ENTER

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#23]
Request from GoldenSilver of the CoG forums [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/299?u=fiogan)

When you search for something, pressing enter repeatedly should jump into the next occurrence of the result. The way it is now is that if you press enter repeatedly it will overwrite the result (because the result comes selected once found).

**Comment by CareyJWilliams** [comment]
You make a good point here: https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/300

If others come forward supporting this change, I'll review this again, but I'll it close for now.
