### ISSUE TITLE
Request for select (highlight) word function

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#24]
From Goldensilver of the CoG forum [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/299?u=fiogan):

> If you select a word, it could highlight the same word if it appears in other locations of the file, making it easier to find *gotos and *labels.

(Example on forum link.)

**Comment by CareyJWilliams** [comment]
Implemented by https://github.com/ChoicescriptIDE/main/commit/aebacdf06677c808a489984faa6c8701403dd877
