### ISSUE TITLE
Dictionary function is underlining correctly-spelled words

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#26]
Reported by atiaxi on the CoG forums [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/302?u=fiogan): 

The dictionary is underlining common words such as 'the' as misspelled, but not all words are underlined either. Screenshot in forum post.

**Comment by CareyJWilliams** [comment]
Pretty sure this was an instance of #8, so I'll close this. But thanks for reporting!
