### ISSUE TITLE
Button or hotkey to jump to next misspelled word

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#27]
Suggestion by GoldenSilver on the CoG forum [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/301?u=fiogan): Add a button or hotkey to jump to the next instance of a misspelling flagged by spellcheck.

**Comment by CareyJWilliams** [comment]
I suspect Monaco's builtin 'jump to next issue' ((opt?) F8 on Mac) will suffice for this: 
![Screenshot 2020-10-11 at 23 14 10](https://user-images.githubusercontent.com/3001447/95691505-8cbe6080-0c17-11eb-9fdc-67f7f51bd6eb.png)

It'll cycle through _all_ issues (as opposed to just spelling errors), but I don't see that being a bad thing.
