### ISSUE TITLE
Cursor jump

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#3]
When focus is on the scene list or the 'run' window and then the editor window is selected, sometimes the text entered will appear several lines away from where the cursor appears. Sometimes certain lines are not clickable at all, and the cursor will appear a few lines above or below.

This was happening with word wrap on, not in full-screen mode, when using iMac with OS Sierra 10.12.4. It is inconsistent, but happened often when only two of the three panels were in view, or when switching between two and three (or two and one) panels. It also happened most often within the internal lines of a word-wrapped paragraph.

**Comment by CareyJWilliams** [comment]
Reopening based on: https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/231?u=cjw
May be a regression, may be unrelated.

**Comment by CareyJWilliams** [comment]
Have you encountered this recently @Fiogan ?

**Comment by Fiogan** [comment]
Yes, I do run across it occasionally. It seems to happen when I have at least one of the side panels collapsed, especially if I've just opened or closed one of them, or changed the font size, or jumped from scene to scene, or all three.

**Comment by CareyJWilliams** [comment]
Thank you for the response! It seems I need to set aside some time to start *using* the IDE if I want to reproduce this. It's one of the long-standing bugs that I would really like to get on top of.

**Comment by CareyJWilliams** [comment]
Unlikely to exist post: [Replace CodeMirror with Monaco](https://github.com/ChoicescriptIDE/main/commit/059c75bec4d1f4a7dcec07a3c2aedc289fda75e5)
