### ISSUE TITLE
CSIDE detecting spaces where there should be only tabs

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#30]
Reported by LaughablyAffable on the CoG forum [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/313?u=fiogan):

CSIDE is reporting spaces on a line where there are only tabs, even after the indentation on the line has been repeatedly deleted and replaced with tabs.

I've had the problem as well, but it was several versions ago, I think? With an imported file.

**Comment by CareyJWilliams** [comment]
Seems to have been a false alarm: https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/316?u=cjw
