### ISSUE TITLE
Showing spaces at the beginning of lines

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#31]
Would it be possible to have a setting which allowed for showing spaces only at the beginning of lines, possibly as dots? That way, space-users could have visual indentation markers as well as tab-users.

**Comment by CareyJWilliams** [comment]
I've rewrote this (tabs included). It now not only supports spaces but should also refuse to mark any inter-mixed indentation (see the middle and last line in the attached picture).

<img width="285" alt="screen shot 2017-12-16 at 00 10 32" src="https://user-images.githubusercontent.com/3001447/34065013-a7bb89ca-e1f5-11e7-92d3-cb7be5c38134.png">
