### ISSUE TITLE
Additional Custom Theme Options

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#42]
_Suggestions for additions to custom themes:_

Support for choosing preferred system font.

Colour change (and maybe width?) for caret/text cursor.

Pronoun highlighting (see: https://github.com/ChoicescriptIDE/main/issues/43)

Colour changes for left sidebar and numbers.

**Comment by CareyJWilliams** [comment]
Most (plus some extras) implemented by: https://github.com/ChoicescriptIDE/main/commit/c492808520fbd6cf91e109bbecea35dc560274ea

I'll handle pronouns from the pronoun ticket if/as/when support is added for them. Font family I think should remain and editor setting, and not be restricted to custom themes (so we'll re-visit this at some point).
