### ISSUE TITLE
Online version, create new project not functioning

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#48]
Online/Dropbox version, Mac, Firefox, current versions:

Create a new project fails: the window to input a name appears, but after the name is entered the window vanishes but the new project does not appear. No corresponding folder is created in Dropbox, as well.

Opening pre-existing projects seems to be fine.

**Comment by CareyJWilliams** [comment]
Hot fix applied on live version: https://github.com/ChoicescriptIDE/web/commit/6ff1a3b34b18286ef1aac9982f1e53e338418e08
