### ISSUE TITLE
Support for additional editor instances

### ISSUE THREAD

**Issue by CareyJWilliams** [ChoicescriptIDE/main#63]
CSIDE would benefit from allowing multiple editor instances of some fashion. The current UI layout may lend itself better to 'floating/pop-out' editors, rather than a traditional split-window format.

**Comment by rkingett** [comment]
I'd like to ask, has the more accessible Monaco Editor been added yet?

**Comment by CareyJWilliams** [comment]
It hasn't, I'm afraid. I'm still (actively) working on it, it's just taking a lot longer than I'd originally expected. Let's track it: https://github.com/ChoicescriptIDE/main/issues/87

**Comment by CareyJWilliams** [comment]
Implemented by https://github.com/ChoicescriptIDE/main/commit/2964637b15ddc132b3cc0073f3fc21764d76a17f
