### ISSUE TITLE
Unable to build on Mac 

### ISSUE THREAD

**Issue by michaelklem** [ChoicescriptIDE/main#74]
Hi.

I am trying to build this project on my Mac PowerBook with OS 10.14.6. I followed the build instructions, but get these errors:

klemm@Macintosh-3:~/Sites/choicescript/main>grunt build-with-mac
(node:48970) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Running "clean:files" (clean) task
>> 9 paths cleaned.

Running "clean:folders" (clean) task
>> 1 path cleaned.

Running "auto_install:codemirror_npm" (auto_install) task
running npm install cside-codemirror on ...npm WARN grunt-execute@0.2.2 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN CSIDE@1.3.1 No repository field.
npm WARN CSIDE@1.3.1 No license field.

+ cside-codemirror@5.30.0
added 1 package in 16.098s
✔

Running "auto_install:codemirror" (auto_install) task
running npm install  on node_modules/cside-codemirror...npm WARN deprecated rollup-watch@3.2.2: rollup-watch functionality is now included in Rollup itself
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> cside-codemirror@5.30.0 prepare /Users/klemm/Sites/choicescript/main/node_modules/cside-codemirror
> npm run-script build

> cside-codemirror@5.30.0 build /Users/klemm/Sites/choicescript/main/node_modules/cside-codemirror
> rollup -c

npm notice created a lockfile as package-lock.json. You should commit this file.
added 38 packages in 3.542s
✔

Running "auto_install:choicescript_npm" (auto_install) task
running npm install cside-choicescript on ...npm WARN grunt-execute@0.2.2 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN CSIDE@1.3.1 No repository field.
npm WARN CSIDE@1.3.1 No license field.

+ cside-choicescript@1.0.0
added 1 package and removed 39 packages in 12.913s
✔

Running "copy:main" (copy) task
Created 18 directories, copied 143 files

Running "concat:dist" (concat) task
Warning: Could not find: node_modules/cside-codemirror/lib/codemirror.js Use --force to continue.

Aborted due to warnings.
klemm@Macintosh-3:~/Sites/choicescript/main>node -v
v8.11.2
klemm@Macintosh-3:~/Sites/choicescript/main>npm -v
5.6.0

Any ideas?

**Comment by CareyJWilliams** [comment]
Hi! Yeah, it sounds like Running "auto_install:codemirror" (auto_install) task isn't working properly. You should try using npm 6.1.0+, as recommended on the home page, though I appreciate that 5.6.0 is what ships with Node v8.11.2, I have had issues with using it for that particular module before.

**Comment by CareyJWilliams** [comment]
Closing on the assumption that this was resolved/was due to unsupported tool versions.
