### ISSUE TITLE
Monaco Editor

### ISSUE THREAD

**Issue by CareyJWilliams** [ChoicescriptIDE/main#87]

**Comment by rkingett** [comment]
Ah yes. I'll track it here! Thanks! I tried to download the latest stable again to test it, but I think I will wait for a beta version with this editor to test.

**Comment by CareyJWilliams** [comment]
The explicit change was made as part by 059c75bec4d1f4a7dcec07a3c2aedc289fda75e5.
There's still a lot of work to do on enhancements, but I think we're at rough feature parity now.

**Comment by rkingett** [comment]
yay! Is there a packaged beta to test, on Windows?
