### ISSUE TITLE
Alpha testing within the IDE?

### ISSUE THREAD

**Issue by ebpatton** [ChoicescriptIDE/main#96]
Is there a practical way to do alpha testing within the IDE?  I'm thinking of a large project.  You get, say, halfway through (or whatever) and you don't want to have to keep playing from the beginning just to test.  Yes, I can export it and use the Save plugins for Choice Script, but then I'm no longer within the IDE.  Is there a way to, say, write my variables to a text file so I import them later?  Or any way to save the state of the game within the IDE so I can just do all my testing within it?

**Comment by CareyJWilliams** [comment]
Sorry the extremely late reply. This slipped under the radar. I'm not sure if this will still be useful to you, but someone else may stumble across it: Yes, but you'll need to use the console (there's documentation about it in the Help Tab).

1. Write up a scene file (e.g. alpha_stats.txt) that uses \*set to re-configure all the variables you want changed from their startup.txt value (this does have to be done manually at the moment)
2. Run your game
3. Use the console to \*goto_scene (or \*gosub_scene) your variable file above (e.g. \*gosub_scene alpha_stats.txt).
4. Finally, use the console to \*goto_scene alpha_test_scene alpha_test_label

Just bear in mind that \*goto_scene from the console allows you to get yourself into strange stats that wouldn't be possible in a normal run-through. Thus it's really important to make sure you've configured all the necessary variables sensibly before you do the jump.
